server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sproopesh/centralized-location
          username: sproopesh73@gmail.com
          password: P@ssw0rd@73$$
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 